# Generated by Django 5.0.2 on 2024-03-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session_year',
            old_name='Session_end',
            new_name='semester',
        ),
        migrations.RemoveField(
            model_name='session_year',
            name='Session_start',
        ),
    ]
