# Generated by Django 5.0.2 on 2024-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_session_end_session_year_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(default='YourDefaultValueHere', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='registration',
            field=models.CharField(default='YourDefaultValueHere', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.CharField(default='YourDefaultValueHere', max_length=20),
        ),
    ]
