# Generated by Django 5.0.2 on 2024-03-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_student_mobile_number_student_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
