# Generated by Django 5.0.2 on 2024-03-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_student_created_at_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
