# Generated by Django 5.0.2 on 2024-03-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_department_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='hod',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id_num',
        ),
        migrations.RemoveField(
            model_name='course',
            name='num_student',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
    ]
