# Generated by Django 5.0.2 on 2024-03-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_course_hod_remove_course_id_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
    ]
