# Generated by Django 5.0.2 on 2024-03-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_course_hod_course_id_num_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration',
            field=models.IntegerField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
