# Generated by Django 5.0.2 on 2024-03-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
    ]
