# Generated by Django 5.0.2 on 2024-03-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Experience',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Qualification',
            field=models.TextField(default='', null=True),
        ),
    ]
