# Generated by Django 5.0.2 on 2024-04-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'TEACHER'), (3, 'STUDENT')], default=1, max_length=7),
        ),
    ]
